import { Voucher, Category } from './types';

export const categories: Category[] = [
  {
    id: 'gaming',
    name: 'Gaming',
    icon: 'Gamepad2',
    description: 'Gaming platforms and in-game currencies',
    count: 45,
    featured: true,
  },
  {
    id: 'streaming',
    name: 'Streaming',
    icon: 'Play',
    description: 'Entertainment and streaming services',
    count: 28,
    featured: true,
  },
  {
    id: 'shopping',
    name: 'Shopping',
    icon: 'Shopping',
    description: 'Retail and e-commerce platforms',
    count: 67,
    featured: true,
  },
  {
    id: 'food',
    name: 'Food & Dining',
    icon: 'UtensilsCrossed',
    description: 'Restaurants and food delivery',
    count: 34,
  },
  {
    id: 'travel',
    name: 'Travel',
    icon: 'Plane',
    description: 'Hotels, flights, and travel services',
    count: 23,
  },
  {
    id: 'crypto',
    name: 'Crypto',
    icon: 'Bitcoin',
    description: 'Cryptocurrency and DeFi platforms',
    count: 19,
  },
];

export const featuredVouchers: Voucher[] = [
  {
    id: '1',
    title: 'Steam Gift Card',
    description: 'Access thousands of games on the world\'s largest gaming platform',
    category: 'gaming',
    brand: 'Steam',
    price: 25,
    originalPrice: 25,
    image: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['Instant delivery', 'No expiry date', 'Global redemption'],
    termsAndConditions: 'Valid for Steam purchases only. Cannot be exchanged for cash.',
    stockCount: 150,
    rating: 4.8,
    reviewCount: 2341,
    isPopular: true,
    deliveryTime: 'Instant',
  },
  {
    id: '2',
    title: 'Netflix Premium',
    description: '1 month of Netflix Premium with 4K streaming',
    category: 'streaming',
    brand: 'Netflix',
    price: 15.99,
    originalPrice: 19.99,
    discount: 20,
    image: 'https://images.pexels.com/photos/4009402/pexels-photo-4009402.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['4K Ultra HD', '4 screens', 'Download offline'],
    termsAndConditions: 'Valid for new accounts only. Auto-renewal after trial.',
    stockCount: 89,
    rating: 4.6,
    reviewCount: 1876,
    isNew: true,
    deliveryTime: 'Instant',
  },
  {
    id: '3',
    title: 'Amazon Gift Card',
    description: 'Shop millions of products on Amazon with this gift card',
    category: 'shopping',
    brand: 'Amazon',
    price: 50,
    originalPrice: 50,
    image: 'https://images.pexels.com/photos/4465124/pexels-photo-4465124.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['No fees', 'Never expires', 'Millions of items'],
    termsAndConditions: 'Valid on Amazon.com for eligible purchases only.',
    stockCount: 234,
    rating: 4.9,
    reviewCount: 5432,
    isPopular: true,
    deliveryTime: 'Instant',
  },
  {
    id: '4',
    title: 'PlayStation Store',
    description: 'PlayStation Store credit for games, add-ons, and subscriptions',
    category: 'gaming',
    brand: 'PlayStation',
    price: 30,
    originalPrice: 30,
    image: 'https://images.pexels.com/photos/1464218/pexels-photo-1464218.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['PS4 & PS5 compatible', 'Instant delivery', 'No expiry'],
    termsAndConditions: 'Valid for PlayStation Network purchases only.',
    stockCount: 67,
    rating: 4.7,
    reviewCount: 987,
    deliveryTime: 'Instant',
  },
  {
    id: '5',
    title: 'Uber Eats Voucher',
    description: 'Free delivery and discounts on your favorite restaurants',
    category: 'food',
    brand: 'Uber Eats',
    price: 20,
    originalPrice: 25,
    discount: 20,
    image: 'https://images.pexels.com/photos/4393021/pexels-photo-4393021.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['Free delivery', 'No minimum order', 'Valid 6 months'],
    termsAndConditions: 'Valid for food delivery orders only. Expires in 6 months.',
    stockCount: 145,
    rating: 4.4,
    reviewCount: 654,
    deliveryTime: 'Instant',
  },
  {
    id: '6',
    title: 'Spotify Premium',
    description: '3 months of ad-free music streaming',
    category: 'streaming',
    brand: 'Spotify',
    price: 29.99,
    originalPrice: 35.97,
    discount: 17,
    image: 'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg?auto=compress&cs=tinysrgb&w=800',
    features: ['Ad-free music', 'Offline downloads', 'High quality audio'],
    termsAndConditions: 'Valid for new Premium subscribers only.',
    stockCount: 203,
    rating: 4.5,
    reviewCount: 1234,
    deliveryTime: 'Instant',
  },
];

export const popularBrands = [
  'Steam', 'Netflix', 'Amazon', 'PlayStation', 'Xbox', 'Spotify', 'Apple', 'Google',
  'Uber', 'DoorDash', 'Airbnb', 'Booking.com', 'Nike', 'Adidas', 'Starbucks', 'McDonald\'s'
];